In [3]:
import os
os.getcwd()



'C:\\Users\\91928\\Desktop\\datascience\\employee-attrition-ml'

In [5]:
import pandas as pd

df = pd.read_csv("data/employee_attrition.csv")
df.head()


Age\tAttrition\tBusinessTravel\tDailyRate\tDepartment\tDistanceFromHome\tEducation\tEducationField\tEmployeeCount\tEmployeeNumber\tEnvironmentSatisfaction\tGender\tHourlyRate\tJobInvolvement\tJobLevel\tJobRole\tJobSatisfaction\tMaritalStatus\tMonthlyIncome\tMonthlyRate\tNumCompaniesWorked\tOver18\tOverTime\tPercentSalaryHike\tPerformanceRating\tRelationshipSatisfaction\tStandardHours\tStockOptionLevel\tTotalWorkingYears\tTrainingTimesLastYear\tWorkLifeBalance\tYearsAtCompany\tYearsInCurrentRole\tYearsSinceLastPromotion\tYearsWithCurrManager
0  41\tYes\tTravel_Rarely\t1102\tSales\t1\t2\tLif...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
1  49\tNo\tTravel_Frequently\t279\tResearch & Dev...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
2  37\tYes\tTravel_Rarely\t1373\tResearch & Devel...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
3  33\tNo\tTravel_Frequently\t1392\tResearch & De...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
4  27\tNo\tTravel_Rarely\t591\tResearch & Develop...

In [7]:
df.shape


(1470, 1)

In [9]:
df.columns


Index(['Age\tAttrition\tBusinessTravel\tDailyRate\tDepartment\tDistanceFromHome\tEducation\tEducationField\tEmployeeCount\tEmployeeNumber\tEnvironmentSatisfaction\tGender\tHourlyRate\tJobInvolvement\tJobLevel\tJobRole\tJobSatisfaction\tMaritalStatus\tMonthlyIncome\tMonthlyRate\tNumCompaniesWorked\tOver18\tOverTime\tPercentSalaryHike\tPerformanceRating\tRelationshipSatisfaction\tStandardHours\tStockOptionLevel\tTotalWorkingYears\tTrainingTimesLastYear\tWorkLifeBalance\tYearsAtCompany\tYearsInCurrentRole\tYearsSinceLastPromotion\tYearsWithCurrManager'], dtype='object')

In [13]:
df = pd.read_csv("data/employee_attrition.csv", sep="\t")
df.head()



Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   
4   27        No      Travel_Rarely        591  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   
2                 2          2          Other              1               4   
3                 3          4  Life Sciences              1               5   
4                 2          1        Medical              1               7   

   ...  RelationshipSatisfaction StandardHours  StockOptionLevel  \
0  ...                         1            80                 0   
1  ...                         4            80                 1   
2  ...                         2            80                 0   
3  ...                         3            80                 0   
4  ...                         4            80                 1   

   TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                  8                      0               1               6   
1                 10                      3               3              10   
2                  7                      3               3               0   
3                  8                      3               3               8   
4                  6                      3               3               2   

  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                  4                        0                     5  
1                  7                        1                     7  
2                  0                        0                     0  
3                  7                        3                     0  
4                  2                        2                     2  

[5 rows x 35 columns]

In [15]:
df['Attrition'].value_counts()


Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [17]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Age                       1470 non-null   int64 
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64 
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64 
 6   Education                 1470 non-null   int64 
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64 
 9   EmployeeNumber            1470 non-null   int64 
 10  EnvironmentSatisfaction   1470 non-null   int64 
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64 
 13  JobInvolvement            1470 non-null   int64 
 14  JobLevel                

In [19]:
cols_to_drop = [
    'EmployeeCount',
    'EmployeeNumber',
    'Over18',
    'StandardHours'
]

df = df.drop(columns=cols_to_drop)


In [21]:
df.columns


Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='object')

In [23]:
df['Attrition'] = df['Attrition'].map({'No': 0, 'Yes': 1})


In [25]:
df['Attrition'].value_counts()


Attrition
0    1233
1     237
Name: count, dtype: int64

In [27]:
df.groupby('OverTime')['Attrition'].mean()


OverTime
No     0.104364
Yes    0.305288
Name: Attrition, dtype: float64

In [29]:
df.groupby('JobSatisfaction')['Attrition'].mean()


JobSatisfaction
1    0.228374
2    0.164286
3    0.165158
4    0.113290
Name: Attrition, dtype: float64

In [31]:
X = df.drop('Attrition', axis=1)
y = df['Attrition']


In [33]:
X.shape, y.shape


((1470, 30), (1470,))

In [37]:
X_encoded = pd.get_dummies(X, drop_first=True)


In [39]:
X_encoded.shape


(1470, 44)

In [41]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


In [43]:
X_train.shape, X_test.shape


((1176, 44), (294, 44))

In [49]:
from sklearn.linear_model import LogisticRegression

model_lr = LogisticRegression(max_iter=3000)
model_lr.fit(X_train, y_train)


C:\Users\91928\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=3000)

In [47]:
y_pred_lr = model_lr.predict(X_test)


In [51]:
from sklearn.metrics import confusion_matrix, classification_report

confusion_matrix(y_test, y_pred_lr)


array([[245,   2],
       [ 37,  10]], dtype=int64)

In [59]:
print(classification_report(y_test, y_pred_lr))


              precision    recall  f1-score   support

           0       0.87      0.99      0.93       247
           1       0.83      0.21      0.34        47

    accuracy                           0.87       294
   macro avg       0.85      0.60      0.63       294
weighted avg       0.86      0.87      0.83       294



The logistic regression model achieves high accuracy, but has very low recall for attrition. Since missing a high-risk employee is costly, this model is not suitable for decision-making and serves only as a baseline.

In [61]:
from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight='balanced'
)

model_rf.fit(X_train, y_train)


RandomForestClassifier(class_weight='balanced', n_estimators=200,
                       random_state=42)

In [63]:
y_pred_rf = model_rf.predict(X_test)


In [65]:
from sklearn.metrics import confusion_matrix, classification_report

confusion_matrix(y_test, y_pred_rf)


array([[242,   5],
       [ 43,   4]], dtype=int64)

In [67]:
print(classification_report(y_test, y_pred_rf))


              precision    recall  f1-score   support

           0       0.85      0.98      0.91       247
           1       0.44      0.09      0.14        47

    accuracy                           0.84       294
   macro avg       0.65      0.53      0.53       294
weighted avg       0.78      0.84      0.79       294



A more complex model does not automatically give better business outcomes. Model evaluation must align with the cost of errors

In [70]:
y_prob_rf = model_rf.predict_proba(X_test)[:, 1]


In [73]:
import numpy as np

# try a lower threshold
threshold = 0.3

y_pred_rf_03 = (y_prob_rf >= threshold).astype(int)


In [75]:
from sklearn.metrics import classification_report, confusion_matrix

confusion_matrix(y_test, y_pred_rf_03)


array([[227,  20],
       [ 30,  17]], dtype=int64)

In [77]:
print(classification_report(y_test, y_pred_rf_03))


              precision    recall  f1-score   support

           0       0.88      0.92      0.90       247
           1       0.46      0.36      0.40        47

    accuracy                           0.83       294
   macro avg       0.67      0.64      0.65       294
weighted avg       0.82      0.83      0.82       294



We deliberately lowered the decision threshold to improve recall for attrition, prioritizing business cost over raw accuracy

In [80]:
results = X_test.copy()
results['Actual_Attrition'] = y_test.values
results['Attrition_Probability'] = y_prob_rf


In [82]:
def risk_bucket(p):
    if p >= 0.6:
        return 'High'
    elif p >= 0.3:
        return 'Medium'
    else:
        return 'Low'

results['Risk_Level'] = results['Attrition_Probability'].apply(risk_bucket)


In [84]:
results['Risk_Level'].value_counts()


Risk_Level
Low       257
Medium     32
High        5
Name: count, dtype: int64